CREATE FUNCTION EOMonth (
	@Date AS DATE
)
RETURNS [DATE]
AS
BEGIN
	DECLARE @EOMonth DATETIME
	SELECT @EOMonth = CAST(DATEADD(MONTH, DATEDIFF(MONTH, 0, @Date) + 1 , 0) - 1  AS DATE)
	RETURN @EOMonth
END